version: '2.1'
orbs:
  maven: circleci/maven@1.4.1
jobs:
    build:
      docker:
        - image: maven@1.4.1
    test:
      command: mvn test
      steps:
        - run:
            name: Save test results
            command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            when: always
        - store_test_results:
            path: ~/test-results

